management:
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include: '*'
logging:
  level:
    ROOT: ERROR
    org.apache.cxf.services: DEBUG
    org.springframework: ERROR
    org.springframework.boot.context.config: ERROR
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
pattern:
  console: "%d %-5level %logger : %msg%n"
#server.ssl.key-store: classpath:vjassal-uber.p12
#server.ssl.key-store-password: changeit
#server.ssl.key-password: changeit
#trust-store: src/main/resources/client-truststore.p12
#trust-store-password: changeit
#server.port: ${SERVER_PORT:8282}
server.port: 8282
#server.port: 0

spring.application.name: rest-eureka-client

spring:
  zipkin:
    base-url: http://${ZIPKIN_CONTAINER_NAME:localhost}:9411/
    sender.type: web

  sleuth:
    sampler:
      probability: 1

  jpa:
    hibernate.ddl-auto: update
    use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  jta:
    atomikos:
      properties:
        log-base-dir: /app/atomikos-tlogs
        max-timeout: 900000


## MySQL
spring.datasource:
  url: jdbc:mysql://${MYSQL_CONTAINER_NAME:localhost}:3306/${MYSQL_DATABASE:uber_eats}?pinGlobalTxToPhysicalConnection=true
  username: ${MYSQL_USER:user}
  password: ${MYSQL_PASSWORD:password}

java:
  naming:
    provider:
      url: tcp://${SPRING_ACTIVEMQ_BROKER_URL:localhost}:61616?consumerMaxRate=1

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/

info.app.name: rest-eureka-client
info.app.description: This is rest-eureka-client
info.app.version: 1.0.0